//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyShell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chek()
        {
            this.Sell = new HashSet<Sell>();
        }
    
        public int IdCheck { get; set; }
        public int IdSeller { get; set; }
        public int IdCustomer { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sell> Sell { get; set; }
        public virtual Customer Customer1 { get; set; }
    }
}
