//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsyShell
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell
    {
        public int IdSell { get; set; }
        public int IdProduct { get; set; }
        public int IdCheck { get; set; }
    
        public virtual Chek Chek { get; set; }
        public virtual Product Product { get; set; }
    }
}
